#!/bin/bash

## Uncomment to change display language to english
# LANGUAGE=en

clear
if [ "$LANGUAGE" = "en" ]; then
    printf "q - exit\n"
else
    printf "q - wyjście\n"
fi

while :; do
    if [ "$LANGUAGE" = "en" ]; then
        printf "\nTranslate pl->en: "
    else
        printf "\nTłumacz pl->en: "
    fi
    read word
    # clear
    if [ "$word" = "q" ]; then
        exit 0
    fi
    links -dump http://megaslownik.pl/slownik/polsko_angielski/$word | grep "\[IMG\]>>" | sed -e 's/\[IMG\]//'
done
